[versions]
kotlin = "2.3.10"
agp = "9.0.0"
compileSdk = "36"
material3 = "1.10.0-alpha05"
compose = "1.10.1"
publish = "0.36.0"

[libraries]
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
multiplatform-android-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
gradle-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }